# Generated by Django 3.1.7 on 2021-04-19 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20210419_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='location',
            field=models.CharField(default='Tokyo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='title',
            field=models.CharField(default='Amazing walk through Tokyo', max_length=100),
            preserve_default=False,
        ),
    ]
