# Generated by Django 3.1.7 on 2021-04-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20210419_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=2.2, max_digits=10),
            preserve_default=False,
        ),
    ]
