# Generated by Django 3.1.7 on 2021-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20210508_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='starting_location',
        ),
        migrations.AddField(
            model_name='map',
            name='starting_location_1',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='starting_location_2',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='cover',
            field=models.ImageField(upload_to='images/', verbose_name='Cover picture:'),
        ),
        migrations.AlterField(
            model_name='map',
            name='long',
            field=models.ImageField(upload_to='images/', verbose_name='Portrait picture:'),
        ),
        migrations.AlterField(
            model_name='map',
            name='small_1',
            field=models.ImageField(upload_to='images/', verbose_name='A small picture:'),
        ),
        migrations.AlterField(
            model_name='map',
            name='small_2',
            field=models.ImageField(upload_to='images/', verbose_name='A small picture (one more for good luck):'),
        ),
    ]
