# Generated by Django 3.1.7 on 2021-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20210508_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CC_FIPS', models.CharField(max_length=2)),
                ('CC_ISO', models.CharField(max_length=2)),
                ('FULL_NAME_ND', models.CharField(max_length=100)),
            ],
        ),
    ]
