# Generated by Django 3.1.7 on 2021-05-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20210513_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CC_FIPS', models.CharField(max_length=2)),
                ('CC_ISO', models.CharField(max_length=2)),
                ('COUNTRY_NAME', models.CharField(max_length=100)),
            ],
        ),
    ]
