# Generated by Django 3.1.7 on 2021-05-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20210514_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='location',
            new_name='starting_location',
        ),
        migrations.AddField(
            model_name='map',
            name='country_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='maps.country'),
        ),
        migrations.AddField(
            model_name='map',
            name='state_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='maps.state'),
        ),
    ]
