# Generated by Django 3.1.7 on 2021-05-17 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_auto_20210514_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='duration',
        ),
        migrations.AddField(
            model_name='map',
            name='duration_hours',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='duration_minutes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
            preserve_default=False,
        ),
    ]
